from openea.expriment.approaches_without_attribute.jape import JAPE
from openea.expriment.approaches_without_attribute.attre import AttrE
from openea.expriment.approaches_without_attribute.imuse import IMUSE
from openea.expriment.approaches_without_attribute.multi_ke import MultiKE
from openea.expriment.approaches_without_attribute.gcn_align import GCN_Align
from openea.expriment.approaches_without_attribute.rdgcn import RDGCN